### ISSUE TITLE
Shouldn't this be input?

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/xvega#32]
https://github.com/QuantStack/xvega/blob/d6e0c35f65e9ccb88be99ee814637f1971ea421a/include/xvega/grammar/encodings/encoding-channels/position-channels/x.hpp#L36

**Comment by madhur-tandon** [comment]
Oh no, this is imputation (see https://vega.github.io/vega-lite/docs/impute.html). It defines what to do with missing values.
